/**
 * 面板的 zh/en 字典。独立成文件是为了让 index.tsx 回归纯 wiring：
 * 一百多行的文案字面量挤在装配代码里，读接线逻辑要在字典里翻找。
 *
 * 导出是为了让测试能拿枚举交叉断言：面板里的 t() 全是运行时拼出来的 key
 * (`role.${member.role}` / `reason.${...}` / `status.${...}`)，而 Translator
 * 接受任意字符串 —— 新增枚举值忘了配字典，面板会把原始 key 直接渲染出来，
 * 编译器和现有测试都不会响。
 */
export const zh = {
  'panel.title': '自动驾驶：{team}',
  'panel.summary': '{members} 名成员（{busy} 忙碌） · {tasks} 个进行中任务 · {escalations} 个待处理升级',
  'section.members': '成员与工作空间',
  'section.cycles': '迭代周期',
  'section.tasks': '任务看板',
  'section.escalations': '升级事件',
  'section.deploys': '部署历史',
  'section.learnings': '已知教训',
  'section.metrics': '运行指标',
  'section.blocked': '卡住的任务',
  'section.awaiting': '等你决策',
  'section.questionnaires': '问卷流水',
  'section.metrics.hint': '派发/完成、返工轮数、质量门与部署统计',
  'section.blocked.hint': '前置无法满足、等人工分诊或等澄清的任务',
  'section.questionnaires.hint': 'AI 向你提问的问卷记录（含已答复/超时/取消）',
  'section.learnings.hint': '从评审打回与升级沉淀的教训，按被印证次数排序',
  'section.escalations.hint': 'AI 卡住时叫你来分诊的事件',
  'section.deploys.hint': '部署与回滚历史',
  'section.activity': '最近动态',
  'section.activity.hint': '按时间倒序的最近动态（评审/升级/部署/问卷/教训）',
  'activity.empty': '暂无动态',
  'activity.review': '评审',
  'activity.escalation': '升级',
  'activity.deploy': '部署',
  'activity.questionnaire': '问卷',
  'activity.learning': '教训',
  'review.approve': '通过',
  'review.request_changes': '打回',
  'loop.stopped': '已停止',
  'loop.running': '运行中',
  'loop.paused': '已暂停',
  'loop.escalated': '已升级',
  'loop.completed': '已完成',
  'phase.intake': '需求澄清',
  'phase.kickoff_pending_approval': '待批开工包',
  'phase.scaffolding': '搭骨架',
  'phase.developing': '开发中',
  'phase.replanning': '重排计划',
  'phase.notDispatching': '当前阶段不派发新任务',
  'cycleStatus.planned': '已规划',
  'cycleStatus.in_progress': '进行中',
  'cycleStatus.in_review': '验收中',
  'cycleStatus.done': '已完成',
  'cycles.active': '当前周期',
  'cycles.progress': '{done}/{total} 已完成',
  'role.leader': '组长',
  'role.developer': '开发',
  'role.reviewer': '审查',
  'role.operator': '运维',
  'status.pending': '待办',
  'status.in_progress': '进行中',
  'status.in_review': '审查中',
  'status.changes_requested': '待修改',
  'status.needs-clarification': '待澄清',
  'status.done': '已完成',
  'status.needs-human': '待人工',
  'status.cancelled': '已废弃',
  'task.round': '第 {round} 轮返工',
  'task.roundHint': '评审被打回后正在返工',
  'task.expand': '点击展开详情',
  'kanban.searchPlaceholder': '搜索任务…',
  'kanban.allMembers': '全部成员',
  'kanban.allCycles': '全部周期',
  'kanban.noMatch': '没有匹配的任务',
  'gates.badge': '门 {passed}/{total}',
  'gates.tooltip': '质量门（质量检查命令），全部通过才可合并',
  'ci.pending': 'CI 等待',
  'ci.success': 'CI 通过',
  'ci.failure': 'CI 失败',
  'ci.unknown': 'CI 未知',
  'escalations.empty': '暂无升级事件',
  'blocked.empty': '没有被卡住的任务',
  'questionnaires.empty': '暂无已答复的问卷',
  'awaiting.empty': '没有在等你的决定',
  'awaiting.count': '{count} 项等你决策',
  'awaiting.hint': '这些单子没有故障 —— AI 团队在等人做选择才能继续',
  'actions.title': '待办中心',
  'actions.hint': '需要你处理的事项（问卷/升级/卡住/待人工）',
  'actions.empty': '暂无待办',
  'actions.count': '{count} 项待办',
  'actions.questionnaires': '等你决策',
  'actions.escalations': '待分诊升级',
  'actions.blocked': '卡住的任务',
  'actions.needsHuman': '待人工任务',
  'questionnaire.onTask': '等人回答',
  'questionnaire.open': '等你回答',
  'questionnaire.answered': '已答复',
  'questionnaire.expired': '已超时（按各题默认方案继续）',
  'questionnaire.cancelled': '已取消',
  'questionnaire.awaitingLeader': '已答复，等组长继续',
  'questionnaire.submit': '提交答复',
  'questionnaire.submitting': '提交中…',
  'questionnaire.submitted': '已提交，等待面板刷新确认',
  'questionnaire.continueHint': '答完请回会话说一句「继续」，组长才会接着跑',
  'questionnaire.failed': '提交失败，请稍后重试或改用邮件里的工单链接',
  'questionnaire.missing': '；还有必填项没答：{missing}',
  'questionnaire.optional': '（选填）',
  'questionnaire.choose': '请选择…',
  'questionnaire.kind.intake': '需求澄清',
  'questionnaire.kind.approval': '文档审批',
  'questionnaire.kind.replan': '重排确认',
  'questionnaire.kind.cycle': '周期边界确认',
  'questionnaire.mode.interactive': '这一轮正挂起等人回答；答完组长立即继续',
  'questionnaire.mode.async': '异步提问：答完请回会话说一句「继续」',
  'escalation.decisionLabel': '请确认如何处理该问题（填写你的决策）',
  'escalation.decisionPlaceholder': '例如：同意该方案 / 更换密钥 / 变更需求……',
  'escalation.noteLabel': '补充说明（可选；密钥请通过环境变量提供，勿直接粘贴）',
  'escalation.notePlaceholder': '任何需要 AI 团队知道的上下文',
  'escalation.applySuggestion': '按建议执行',
  'deploys.empty': '暂无部署记录',
  'learnings.empty': '暂无沉淀的教训',
  'learnings.hits': '已印证 {hits} 次',
  'learnings.promoted': '已升格',
  'deploy.running': '部署中',
  'deploy.healthy': '健康',
  'deploy.failed': '失败',
  'deploy.rolled-back': '已回滚',
  'deploy.rollback-failed': '回滚失败',
  'reason.conflicting-requirements': '需求矛盾',
  'reason.cross-domain': '跨域改动',
  'reason.paid-dependency': '付费依赖',
  'reason.foreign-gate-failure': '非本任务门红',
  'reason.forbidden-paths': '触及禁区',
  'reason.review-rounds-exceeded': '返工超限',
  'reason.change-too-large': '改动过大',
  'reason.blocked-dependency': '前置无法满足',
  'reason.task-stuck': '任务卡死',
  'reason.deploy-failed': '部署失败',
  'reason.bootstrap-failed': '引导失败',
  'reason.gate-failure': '质量门失败',
  'reason.manual': '人工升级',
  'reason.budget-exceeded': '超出墙钟预算',
  'metrics.dispatched': '派发 {dispatched} / 完成 {completed}',
  'metrics.reviewRounds': '返工 {reviewRounds} 轮',
  'metrics.gates': '门 {gateRuns} 次（失败 {gateFailures}）',
  'metrics.deploys': '部署 {deploys} 次（回滚 {rollbacks}）',
  'notify.disabled': '未启用通知',
  'notify.sent': '已通知',
  'notify.failed': '通知失败',
  'notify.submitted': '已答复',
  'notify.off': '提醒',
  'notify.on': '提醒中',
  'notify.denied': '浏览器已拒绝通知权限',
  'notify.escalationTitle': '自动驾驶需要你',
  'config.intro': '编辑 autopilot 的关键配置。改动保存后即时热生效，无需重启；remote.url 只影响新建团队。',
  'config.remoteUrl': '远端仓库地址',
  'remoteUrlHint': 'git@github.com:org/repo.git 或 https 地址；可为空仓库。',
  'config.baseBranch': '基础分支',
  'config.bootstrapEnabled': '启用引导',
  'config.gatesCommands': '质量门命令（每行一条）',
  'gatesCommandsHint': '每行一条，按顺序执行；全绿才允许合并。',
  'config.maxReviewRounds': '最大返工轮次',
  'config.stuckMinutes': '卡死判定期（分钟）',
  'config.maxDiffLines': '评审体量上限（行，0=关闭）',
  'maxDiffLinesHint': '单任务累计增删行超过这个数就不许 approve，改为升级让人决定是拆任务还是放行。',
  'config.learningsEnabled': '启用知识回路',
  'learningsEnabledHint': '把评审打回与升级沉淀成教训，注入后续任务描述；只写台账，不改项目文档。',
  'config.requireCiGreen': '要求 CI 通过',
  'config.gateTimeoutMinutes': '质量门超时（分钟）',
  'config.pollIntervalSeconds': '轮询间隔（秒）',
  'config.maxTaskHours': '任务墙钟上限（小时）',
  'config.questionnaireTimeoutMinutes': '问卷超时（分钟）',
  'config.maxReplanPerHour': '重排上限（次/小时）',
  'config.pushRequiresGates': '门不过不合并',
  'config.deployEnabled': '启用部署',
  'config.viewFull': '查看完整配置',
  'config.hideFull': '收起完整配置',
  'config.invalidNumber': '请输入有效数字',
  'config.overridden': '已覆盖',
  'config.revert': '还原',
  'config.reset': '重置为继承值',
  'config.discard': '放弃',
  'config.save': '保存',
};

export const en: Record<keyof typeof zh, string> = {
  'panel.title': 'Autopilot: {team}',
  'panel.summary': '{members} members ({busy} busy) · {tasks} in progress · {escalations} open escalations',
  'section.members': 'Members & workspaces',
  'section.cycles': 'Cycles',
  'section.tasks': 'Task board',
  'section.escalations': 'Escalations',
  'section.deploys': 'Deploy history',
  'section.learnings': 'Known lessons',
  'section.metrics': 'Run metrics',
  'section.blocked': 'Blocked tasks',
  'section.awaiting': 'Waiting for you',
  'section.questionnaires': 'Question history',
  'section.metrics.hint': 'Dispatched/done, rework rounds, gate runs and deploys',
  'section.blocked.hint': 'Tasks whose dependency can never be met, or that wait on a human or clarification',
  'section.questionnaires.hint': 'Questionnaire history (answered / expired / cancelled)',
  'section.learnings.hint': 'Lessons distilled from review rejections and escalations, ranked by hits',
  'section.escalations.hint': 'Events raised when the AI team is stuck and needs triage',
  'section.deploys.hint': 'Deploy and rollback history',
  'section.activity': 'Activity',
  'section.activity.hint': 'Recent activity, newest first (reviews / escalations / deploys / questions / lessons)',
  'activity.empty': 'No activity yet',
  'activity.review': 'review',
  'activity.escalation': 'escalation',
  'activity.deploy': 'deploy',
  'activity.questionnaire': 'question',
  'activity.learning': 'lesson',
  'review.approve': 'approved',
  'review.request_changes': 'requested changes',
  'loop.stopped': 'stopped',
  'loop.running': 'running',
  'loop.paused': 'paused',
  'loop.escalated': 'escalated',
  'loop.completed': 'completed',
  'phase.intake': 'intake',
  'phase.kickoff_pending_approval': 'awaiting approval',
  'phase.scaffolding': 'scaffolding',
  'phase.developing': 'developing',
  'phase.replanning': 'replanning',
  'phase.notDispatching': 'This phase dispatches no new tasks',
  'cycleStatus.planned': 'planned',
  'cycleStatus.in_progress': 'in progress',
  'cycleStatus.in_review': 'in review',
  'cycleStatus.done': 'done',
  'cycles.active': 'current',
  'cycles.progress': '{done}/{total} done',
  'role.leader': 'leader',
  'role.developer': 'dev',
  'role.reviewer': 'reviewer',
  'role.operator': 'ops',
  'status.pending': 'Pending',
  'status.in_progress': 'In progress',
  'status.in_review': 'In review',
  'status.changes_requested': 'Changes requested',
  'status.needs-clarification': 'Needs clarification',
  'status.done': 'Done',
  'status.needs-human': 'Needs human',
  'status.cancelled': 'Cancelled',
  'task.round': 'round {round}',
  'task.roundHint': 'Being reworked after the reviewer requested changes',
  'task.expand': 'Click to expand',
  'kanban.searchPlaceholder': 'Search tasks…',
  'kanban.allMembers': 'All members',
  'kanban.allCycles': 'All cycles',
  'kanban.noMatch': 'No matching tasks',
  'gates.badge': 'gates {passed}/{total}',
  'gates.tooltip': 'Quality gates (check commands); all must pass before merge',
  'ci.pending': 'CI pending',
  'ci.success': 'CI green',
  'ci.failure': 'CI failed',
  'ci.unknown': 'CI unknown',
  'escalations.empty': 'No escalations yet',
  'blocked.empty': 'Nothing blocked',
  'questionnaires.empty': 'No answered questionnaires yet',
  'awaiting.empty': 'Nothing waiting for your call',
  'awaiting.count': '{count} waiting for you',
  'awaiting.hint': 'Nothing is broken here — the AI team needs a human decision to continue',
  'actions.title': 'Action center',
  'actions.hint': 'Things needing you (questions / escalations / blocked / needs-human)',
  'actions.empty': 'Nothing pending',
  'actions.count': '{count} action items',
  'actions.questionnaires': 'Waiting for your decision',
  'actions.escalations': 'Escalations to triage',
  'actions.blocked': 'Blocked tasks',
  'actions.needsHuman': 'Tasks needing a human',
  'questionnaire.onTask': 'waiting for you',
  'questionnaire.open': 'waiting for your answer',
  'questionnaire.answered': 'answered',
  'questionnaire.expired': 'expired (defaults applied)',
  'questionnaire.cancelled': 'cancelled',
  'questionnaire.awaitingLeader': 'answered, leader has not resumed',
  'questionnaire.submit': 'Submit answer',
  'questionnaire.submitting': 'Submitting…',
  'questionnaire.submitted': 'Submitted, waiting for the panel to confirm',
  'questionnaire.continueHint': 'Say "continue" in the session so the leader resumes',
  'questionnaire.failed': 'Submit failed; retry later or use the ticket link from the email',
  'questionnaire.missing': '; still missing required answers: {missing}',
  'questionnaire.optional': '(optional)',
  'questionnaire.choose': 'Choose…',
  'questionnaire.kind.intake': 'intake',
  'questionnaire.kind.approval': 'approval',
  'questionnaire.kind.replan': 'replan',
  'questionnaire.kind.cycle': 'cycle boundary',
  'questionnaire.mode.interactive': 'this turn is blocked until you answer; the leader continues right away',
  'questionnaire.mode.async': 'asked asynchronously: answer, then say "continue" in the session',
  'escalation.decisionLabel': 'How should this be handled? (write your decision)',
  'escalation.decisionPlaceholder': 'e.g. approve the proposal / rotate the key / change the requirement…',
  'escalation.noteLabel': 'Additional context (optional; provide secrets via env vars, do not paste them)',
  'escalation.notePlaceholder': 'Any context the AI team should know',
  'escalation.applySuggestion': 'Apply suggestion',
  'deploys.empty': 'No deploys yet',
  'learnings.empty': 'No lessons captured yet',
  'learnings.hits': '{hits} hits',
  'learnings.promoted': 'promoted',
  'deploy.running': 'running',
  'deploy.healthy': 'healthy',
  'deploy.failed': 'failed',
  'deploy.rolled-back': 'rolled back',
  'deploy.rollback-failed': 'rollback failed',
  'reason.conflicting-requirements': 'conflicting requirements',
  'reason.cross-domain': 'cross-domain change',
  'reason.paid-dependency': 'paid dependency',
  'reason.foreign-gate-failure': 'foreign gate failure',
  'reason.forbidden-paths': 'forbidden paths',
  'reason.review-rounds-exceeded': 'rework limit',
  'reason.change-too-large': 'change too large',
  'reason.blocked-dependency': 'unsatisfiable dependency',
  'reason.task-stuck': 'task stuck',
  'reason.deploy-failed': 'deploy failed',
  'reason.bootstrap-failed': 'bootstrap failed',
  'reason.gate-failure': 'gate failure',
  'reason.manual': 'manual escalation',
  'reason.budget-exceeded': 'wall-clock budget exceeded',
  'metrics.dispatched': '{dispatched} dispatched / {completed} done',
  'metrics.reviewRounds': '{reviewRounds} rework rounds',
  'metrics.gates': '{gateRuns} gate runs ({gateFailures} failed)',
  'metrics.deploys': '{deploys} deploys ({rollbacks} rollbacks)',
  'notify.disabled': 'notification off',
  'notify.sent': 'notified',
  'notify.failed': 'notify failed',
  'notify.submitted': 'answered',
  'notify.off': 'alerts',
  'notify.on': 'alerts on',
  'notify.denied': 'Notification permission denied',
  'notify.escalationTitle': 'Autopilot needs you',
  'config.intro': 'Edit autopilot key settings. Changes apply immediately without a restart; remote.url only affects newly created teams.',
  'config.remoteUrl': 'Remote repository URL',
  'remoteUrlHint': 'git@github.com:org/repo.git or an https URL; may be an empty repo.',
  'config.baseBranch': 'Base branch',
  'config.bootstrapEnabled': 'Enable bootstrap',
  'config.gatesCommands': 'Quality-gate commands (one per line)',
  'gatesCommandsHint': 'One per line, run in order; all must pass before a merge.',
  'config.maxReviewRounds': 'Max rework rounds',
  'config.stuckMinutes': 'Stuck threshold (min)',
  'config.maxDiffLines': 'Review size cap (lines, 0=off)',
  'maxDiffLinesHint': 'Above this many changed lines a task cannot be approved; it escalates so a human splits it or waives the cap.',
  'config.learningsEnabled': 'Enable the knowledge loop',
  'learningsEnabledHint': 'Turns review rejections and escalations into lessons injected into later task descriptions; writes a ledger only, never project docs.',
  'config.requireCiGreen': 'Require CI green',
  'config.gateTimeoutMinutes': 'Gate timeout (min)',
  'config.pollIntervalSeconds': 'Poll interval (s)',
  'config.maxTaskHours': 'Task wall-clock cap (h)',
  'config.questionnaireTimeoutMinutes': 'Questionnaire timeout (min)',
  'config.maxReplanPerHour': 'Replan cap (per hour)',
  'config.pushRequiresGates': 'Gates required to merge',
  'config.deployEnabled': 'Enable deploy',
  'config.viewFull': 'View full config',
  'config.hideFull': 'Hide full config',
  'config.invalidNumber': 'Enter a valid number',
  'config.overridden': 'overridden',
  'config.revert': 'Revert',
  'config.reset': 'Reset to inherited',
  'config.discard': 'Discard',
  'config.save': 'Save',
};
