import { ensurePanelStyles } from './styles.js';
import { AutopilotPanel } from './AutopilotPanel.js';
import { AutopilotSettingsCard } from './settings-card.js';
import type { ClientContext } from './contract.js';

/** 依赖的服务：sessions（projection 席位）、slots、locale、settings scope。 */
export const inject = ['sessions', 'slots', 'locale', 'settingsScope'];

/**
 * 导出是为了让测试能拿枚举交叉断言：面板里的 t() 全是运行时拼出来的 key
 * （`role.${member.role}` / `reason.${...}` / `status.${...}`），而 Translator
 * 接受任意字符串 —— 新增枚举值忘了配字典，面板会把原始 key 直接渲染出来，
 * 编译器和现有测试都不会响。
 */
export const zh = {
  'panel.title': '自动驾驶：{team}',
  'panel.summary': '{members} 名成员（{busy} 忙碌） · {tasks} 个进行中任务 · {escalations} 个待处理升级',
  'section.members': '成员与工作空间',
  'section.tasks': '任务看板',
  'section.escalations': '升级事件',
  'section.deploys': '部署历史',
  'section.learnings': '已知教训',
  'section.metrics': '运行指标',
  'section.blocked': '卡住的任务',
  'section.awaiting': '等你决策',
  'section.questionnaires': '问卷流水',
  'loop.stopped': '已停止',
  'loop.running': '运行中',
  'loop.paused': '已暂停',
  'loop.escalated': '已升级',
  'loop.completed': '已完成',
  'phase.intake': '需求澄清',
  'phase.kickoff_pending_approval': '待批开工包',
  'phase.scaffolding': '搭骨架',
  'phase.developing': '开发中',
  'phase.replanning': '重排计划',
  'phase.notDispatching': '当前阶段不派发新任务',
  'role.leader': '组长',
  'role.developer': '开发',
  'role.reviewer': '审查',
  'role.operator': '运维',
  'status.pending': '待办',
  'status.in_progress': '进行中',
  'status.in_review': '审查中',
  'status.changes_requested': '待修改',
  'status.needs-clarification': '待澄清',
  'status.done': '已完成',
  'status.needs-human': '待人工',
  'task.round': '第 {round} 轮返工',
  'gates.badge': '门 {passed}/{total}',
  'ci.pending': 'CI 等待',
  'ci.success': 'CI 通过',
  'ci.failure': 'CI 失败',
  'ci.unknown': 'CI 未知',
  'escalations.empty': '暂无升级事件',
  'blocked.empty': '没有被卡住的任务',
  'questionnaires.empty': '暂无已答复的问卷',
  'awaiting.empty': '没有在等你的决定',
  'awaiting.count': '{count} 项等你决策',
  'awaiting.hint': '这些单子没有故障 —— AI 团队在等人做选择才能继续',
  'questionnaire.onTask': '等人回答',
  'questionnaire.open': '等你回答',
  'questionnaire.answered': '已答复',
  'questionnaire.expired': '已超时（按各题默认方案继续）',
  'questionnaire.cancelled': '已取消',
  'questionnaire.awaitingLeader': '已答复，等组长继续',
  'questionnaire.submit': '提交答复',
  'questionnaire.submitting': '提交中…',
  'questionnaire.submitted': '已提交，等待面板刷新确认',
  'questionnaire.failed': '提交失败，请稍后重试或改用邮件里的工单链接',
  'questionnaire.missing': '；还有必填项没答：{missing}',
  'questionnaire.optional': '（选填）',
  'questionnaire.choose': '请选择…',
  'questionnaire.kind.intake': '需求澄清',
  'questionnaire.kind.approval': '文档审批',
  'questionnaire.kind.replan': '重排确认',
  'questionnaire.mode.interactive': '这一轮正挂起等人回答；答完组长立即继续',
  'questionnaire.mode.async': '异步提问：答完请回会话说一句「继续」',
  'deploys.empty': '暂无部署记录',
  'learnings.empty': '暂无沉淀的教训',
  'learnings.hits': '已印证 {hits} 次',
  'learnings.promoted': '已升格',
  'deploy.running': '部署中',
  'deploy.healthy': '健康',
  'deploy.failed': '失败',
  'deploy.rolled-back': '已回滚',
  'deploy.rollback-failed': '回滚失败',
  'reason.conflicting-requirements': '需求矛盾',
  'reason.cross-domain': '跨域改动',
  'reason.paid-dependency': '付费依赖',
  'reason.foreign-gate-failure': '非本任务门红',
  'reason.forbidden-paths': '触及禁区',
  'reason.review-rounds-exceeded': '返工超限',
  'reason.change-too-large': '改动过大',
  'reason.blocked-dependency': '前置无法满足',
  'reason.task-stuck': '任务卡死',
  'reason.deploy-failed': '部署失败',
  'reason.bootstrap-failed': '引导失败',
  'reason.gate-failure': '质量门失败',
  'reason.manual': '人工升级',
  'reason.budget-exceeded': '超出墙钟预算',
  'metrics.dispatched': '派发 {dispatched} / 完成 {completed}',
  'metrics.reviewRounds': '返工 {reviewRounds} 轮',
  'metrics.gates': '门 {gateRuns} 次（失败 {gateFailures}）',
  'metrics.deploys': '部署 {deploys} 次（回滚 {rollbacks}）',
  'notify.disabled': '未启用通知',
  'notify.sent': '已通知',
  'notify.failed': '通知失败',
  'notify.submitted': '已答复',
  'config.intro': '编辑 autopilot 的关键配置。改动保存后写入用户设置层，下次带 patch 启动时生效。',
  'config.remoteUrl': '远端仓库地址',
  'remoteUrlHint': 'git@github.com:org/repo.git 或 https 地址；可为空仓库。',
  'config.baseBranch': '基础分支',
  'config.bootstrapEnabled': '启用引导',
  'config.gatesCommands': '质量门命令（每行一条）',
  'gatesCommandsHint': '每行一条，按顺序执行；全绿才允许合并。',
  'config.maxReviewRounds': '最大返工轮次',
  'config.stuckMinutes': '卡死判定期（分钟）',
  'config.maxDiffLines': '评审体量上限（行，0=关闭）',
  'maxDiffLinesHint': '单任务累计增删行超过这个数就不许 approve，改为升级让人决定是拆任务还是放行。',
  'config.learningsEnabled': '启用知识回路',
  'learningsEnabledHint': '把评审打回与升级沉淀成教训，注入后续任务描述；只写台账，不改项目文档。',
  'config.overridden': '已覆盖',
  'config.revert': '还原',
  'config.reset': '重置为继承值',
  'config.discard': '放弃',
  'config.save': '保存',
};

export const en: Record<keyof typeof zh, string> = {
  'panel.title': 'Autopilot: {team}',
  'panel.summary': '{members} members ({busy} busy) · {tasks} open tasks · {escalations} open escalations',
  'section.members': 'Members & workspaces',
  'section.tasks': 'Task board',
  'section.escalations': 'Escalations',
  'section.deploys': 'Deploy history',
  'section.learnings': 'Known lessons',
  'section.metrics': 'Run metrics',
  'section.blocked': 'Blocked tasks',
  'section.awaiting': 'Waiting for you',
  'section.questionnaires': 'Question history',
  'loop.stopped': 'stopped',
  'loop.running': 'running',
  'loop.paused': 'paused',
  'loop.escalated': 'escalated',
  'loop.completed': 'completed',
  'phase.intake': 'intake',
  'phase.kickoff_pending_approval': 'awaiting approval',
  'phase.scaffolding': 'scaffolding',
  'phase.developing': 'developing',
  'phase.replanning': 'replanning',
  'phase.notDispatching': 'This phase dispatches no new tasks',
  'role.leader': 'leader',
  'role.developer': 'dev',
  'role.reviewer': 'reviewer',
  'role.operator': 'ops',
  'status.pending': 'Pending',
  'status.in_progress': 'In progress',
  'status.in_review': 'In review',
  'status.changes_requested': 'Changes requested',
  'status.needs-clarification': 'Needs clarification',
  'status.done': 'Done',
  'status.needs-human': 'Needs human',
  'task.round': 'round {round}',
  'gates.badge': 'gates {passed}/{total}',
  'ci.pending': 'CI pending',
  'ci.success': 'CI green',
  'ci.failure': 'CI failed',
  'ci.unknown': 'CI unknown',
  'escalations.empty': 'No escalations yet',
  'blocked.empty': 'Nothing blocked',
  'questionnaires.empty': 'No answered questionnaires yet',
  'awaiting.empty': 'Nothing waiting for your call',
  'awaiting.count': '{count} waiting for you',
  'awaiting.hint': 'Nothing is broken here — the AI team needs a human decision to continue',
  'questionnaire.onTask': 'waiting for you',
  'questionnaire.open': 'waiting for your answer',
  'questionnaire.answered': 'answered',
  'questionnaire.expired': 'expired (defaults applied)',
  'questionnaire.cancelled': 'cancelled',
  'questionnaire.awaitingLeader': 'answered, leader has not resumed',
  'questionnaire.submit': 'Submit answer',
  'questionnaire.submitting': 'Submitting…',
  'questionnaire.submitted': 'Submitted, waiting for the panel to confirm',
  'questionnaire.failed': 'Submit failed; retry later or use the ticket link from the email',
  'questionnaire.missing': '; still missing required answers: {missing}',
  'questionnaire.optional': '(optional)',
  'questionnaire.choose': 'Choose…',
  'questionnaire.kind.intake': 'intake',
  'questionnaire.kind.approval': 'approval',
  'questionnaire.kind.replan': 'replan',
  'questionnaire.mode.interactive': 'this turn is blocked until you answer; the leader continues right away',
  'questionnaire.mode.async': 'asked asynchronously: answer, then say "continue" in the session',
  'deploys.empty': 'No deploys yet',
  'learnings.empty': 'No lessons captured yet',
  'learnings.hits': '{hits} hits',
  'learnings.promoted': 'promoted',
  'deploy.running': 'running',
  'deploy.healthy': 'healthy',
  'deploy.failed': 'failed',
  'deploy.rolled-back': 'rolled back',
  'deploy.rollback-failed': 'rollback failed',
  'reason.conflicting-requirements': 'conflicting requirements',
  'reason.cross-domain': 'cross-domain change',
  'reason.paid-dependency': 'paid dependency',
  'reason.foreign-gate-failure': 'foreign gate failure',
  'reason.forbidden-paths': 'forbidden paths',
  'reason.review-rounds-exceeded': 'rework limit',
  'reason.change-too-large': 'change too large',
  'reason.blocked-dependency': 'unsatisfiable dependency',
  'reason.task-stuck': 'task stuck',
  'reason.deploy-failed': 'deploy failed',
  'reason.bootstrap-failed': 'bootstrap failed',
  'reason.gate-failure': 'gate failure',
  'reason.manual': 'manual escalation',
  'reason.budget-exceeded': 'wall-clock budget exceeded',
  'metrics.dispatched': '{dispatched} dispatched / {completed} done',
  'metrics.reviewRounds': '{reviewRounds} rework rounds',
  'metrics.gates': '{gateRuns} gate runs ({gateFailures} failed)',
  'metrics.deploys': '{deploys} deploys ({rollbacks} rollbacks)',
  'notify.disabled': 'notification off',
  'notify.sent': 'notified',
  'notify.failed': 'notify failed',
  'notify.submitted': 'answered',
  'config.intro': 'Edit autopilot key settings. Changes are written to the user settings layer and take effect on the next patched boot.',
  'config.remoteUrl': 'Remote repository URL',
  'remoteUrlHint': 'git@github.com:org/repo.git or an https URL; may be an empty repo.',
  'config.baseBranch': 'Base branch',
  'config.bootstrapEnabled': 'Enable bootstrap',
  'config.gatesCommands': 'Quality-gate commands (one per line)',
  'gatesCommandsHint': 'One per line, run in order; all must pass before a merge.',
  'config.maxReviewRounds': 'Max rework rounds',
  'config.stuckMinutes': 'Stuck threshold (min)',
  'config.maxDiffLines': 'Review size cap (lines, 0=off)',
  'maxDiffLinesHint': 'Above this many changed lines a task cannot be approved; it escalates so a human splits it or waives the cap.',
  'config.learningsEnabled': 'Enable the knowledge loop',
  'learningsEnabledHint': 'Turns review rejections and escalations into lessons injected into later task descriptions; writes a ledger only, never project docs.',
  'config.overridden': 'overridden',
  'config.revert': 'Revert',
  'config.reset': 'Reset to inherited',
  'config.discard': 'Discard',
  'config.save': 'Save',
};

/** 客户端插件主体。 */
export function apply(ctx: ClientContext): void {
  ensurePanelStyles();
  ctx.effect(() => ctx.locale.register('autopilot', { zh, en }), 'autopilot: dictionaries');
  ctx.slots.inject('conversation.input.dock', () =>
    ctx.slots.register(
      {
        name: 'conversation.input.dock',
        id: 'autopilot',
        order: 40,
        locale: 'autopilot',
      },
      AutopilotPanel,
    ),
  );
  // 设置卡片：把 `autopilot` 这个 Host namespace 与浏览器端卡片配对。
  // 以 namespace 作为 key，这样插件配置页才能把两份账对上。
  const autopilotScope = ctx.settingsScope.bind<Record<string, unknown>>({ namespace: 'autopilot' });
  ctx.slots.inject('settings.plugin.item', () =>
    ctx.slots.register(
      {
        name: 'settings.plugin.item',
        id: 'autopilot',
        key: 'autopilot',
        locale: 'autopilot',
        inject: () => ({ t: ctx.locale.bind('autopilot'), scope: autopilotScope }),
      },
      AutopilotSettingsCard,
    ),
  );
}
