import { ensurePanelStyles } from './styles.js';
import { AutopilotPanel } from './AutopilotPanel.js';
import type { ClientContext } from './contract.js';

/** Required services: sessions (projection seat), slots, locale. */
export const inject = ['sessions', 'slots', 'locale'];

const zh = {
  'panel.title': '自动驾驶：{team}',
  'panel.summary': '{members} 名成员（{busy} 忙碌） · {tasks} 个进行中任务 · {escalations} 个待处理升级',
  'section.members': '成员与工作空间',
  'section.tasks': '任务看板',
  'section.escalations': '升级事件',
  'section.deploys': '部署历史',
  'loop.stopped': '已停止',
  'loop.running': '运行中',
  'loop.paused': '已暂停',
  'loop.escalated': '已升级',
  'loop.completed': '已完成',
  'role.leader': '组长',
  'role.developer': '开发',
  'role.reviewer': '审查',
  'role.operator': '运维',
  'status.pending': '待办',
  'status.in_progress': '进行中',
  'status.in_review': '审查中',
  'status.changes_requested': '待修改',
  'status.done': '已完成',
  'status.needs-human': '待人工',
  'task.round': '第 {round} 轮返工',
  'gates.badge': '门 {passed}/{total}',
  'ci.pending': 'CI 等待',
  'ci.success': 'CI 通过',
  'ci.failure': 'CI 失败',
  'escalations.empty': '暂无升级事件',
  'deploys.empty': '暂无部署记录',
  'deploy.running': '部署中',
  'deploy.healthy': '健康',
  'deploy.failed': '失败',
  'deploy.rolled-back': '已回滚',
  'reason.conflicting-requirements': '需求矛盾',
  'reason.cross-domain': '跨域改动',
  'reason.paid-dependency': '付费依赖',
  'reason.foreign-gate-failure': '非本任务门红',
  'reason.forbidden-paths': '触及禁区',
  'reason.review-rounds-exceeded': '返工超限',
  'reason.task-stuck': '任务卡死',
  'reason.deploy-failed': '部署失败',
  'reason.bootstrap-failed': '引导失败',
  'reason.gate-failure': '质量门失败',
  'reason.manual': '人工升级',
  'notify.disabled': '未启用通知',
  'notify.sent': '已通知',
  'notify.failed': '通知失败',
  'notify.ticket': '工单',
  'notify.submitted': '已答复',
};

const en: Record<keyof typeof zh, string> = {
  'panel.title': 'Autopilot: {team}',
  'panel.summary': '{members} members ({busy} busy) · {tasks} open tasks · {escalations} open escalations',
  'section.members': 'Members & workspaces',
  'section.tasks': 'Task board',
  'section.escalations': 'Escalations',
  'section.deploys': 'Deploy history',
  'loop.stopped': 'stopped',
  'loop.running': 'running',
  'loop.paused': 'paused',
  'loop.escalated': 'escalated',
  'loop.completed': 'completed',
  'role.leader': 'leader',
  'role.developer': 'dev',
  'role.reviewer': 'reviewer',
  'role.operator': 'ops',
  'status.pending': 'Pending',
  'status.in_progress': 'In progress',
  'status.in_review': 'In review',
  'status.changes_requested': 'Changes requested',
  'status.done': 'Done',
  'status.needs-human': 'Needs human',
  'task.round': 'round {round}',
  'gates.badge': 'gates {passed}/{total}',
  'ci.pending': 'CI pending',
  'ci.success': 'CI green',
  'ci.failure': 'CI failed',
  'escalations.empty': 'No escalations yet',
  'deploys.empty': 'No deploys yet',
  'deploy.running': 'running',
  'deploy.healthy': 'healthy',
  'deploy.failed': 'failed',
  'deploy.rolled-back': 'rolled back',
  'reason.conflicting-requirements': 'conflicting requirements',
  'reason.cross-domain': 'cross-domain change',
  'reason.paid-dependency': 'paid dependency',
  'reason.foreign-gate-failure': 'foreign gate failure',
  'reason.forbidden-paths': 'forbidden paths',
  'reason.review-rounds-exceeded': 'rework limit',
  'reason.task-stuck': 'task stuck',
  'reason.deploy-failed': 'deploy failed',
  'reason.bootstrap-failed': 'bootstrap failed',
  'reason.gate-failure': 'gate failure',
  'reason.manual': 'manual escalation',
  'notify.disabled': 'notification off',
  'notify.sent': 'notified',
  'notify.failed': 'notify failed',
  'notify.ticket': 'ticket',
  'notify.submitted': 'answered',
};

/** Client plugin body. */
export function apply(ctx: ClientContext): void {
  ensurePanelStyles();
  ctx.effect(() => ctx.locale.register('autopilot', { zh, en }), 'autopilot: dictionaries');
  ctx.slots.inject('conversation.input.dock', () =>
    ctx.slots.register(
      {
        name: 'conversation.input.dock',
        id: 'autopilot',
        order: 40,
        locale: 'autopilot',
      },
      AutopilotPanel,
    ),
  );
}
